{{- if eq .Values.target "aws" }}
{{- if .Values.postgres.existingVolumeHandle }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-postgres-recovered
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: {{ .Values.postgres.existingVolumeSize | default "10Gi" }}
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: {{ .Values.postgres.existingVolumeHandle }}
  nodeAffinity:
    required:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.ebs.csi.aws.com/zone
                operator: In
                values: [{{ .Values.postgres.existingVolumeAz }}]
{{- end }}
{{- end }}
